### ISSUE TITLE
Adding subinterface

### ISSUE THREAD

**Issue by xibriz** [CiscoDevNet/terraform-provider-fmc#102]
I'm trying to add a Subinterface below a EtherChannel interface.

Is it the `fmc_device_physical_interfaces` resource that is used for this, or is it a resource for subinterface that is not implemented or I am unable to find?

**Comment by kgreeshm** [comment]
Hi,

Thanks for bringing this to our notice. There is a separate API for subinterfaces which is not implemented yet in terraform fmc provider. We will work on it.  

Thanks

**Comment by jeroenwittock** [comment]
Work is in progress to implement this feature, looks like it will become available in the coming weeks.

**Comment by xibriz** [comment]
@jeroenwittock Nice to know :)

I have tested the API directly and observed that the fmc-ansible project has this functionality, but i'm looking forward to the implementation in this Terraform project 👍
