### ISSUE TITLE
Port Groups Needed as Data Sources

### ISSUE THREAD

**Issue by jellyBeanz2019** [CiscoDevNet/terraform-provider-fmc#113]
This request is similar to issue #18 . Would it be possible to add a port group data source that can be created once on the FMC and pulled into x workspaces? Currently, we have to create multiple Terraform port groups resources (fmc_port_group_objects) made up of FMC maintained port objects across every workspace. The end result is multiple, redundant terraform maintained port group objects. Instead, it would be great if we could reference a single, FMC maintained port group object data source and use it across all the workspaces.

**Comment by kgreeshm** [comment]
Hi @jellyBeanz2019 

Thanks for bringing up this to our notice. We are working on it. Will add it :)

Thanks 
Greeshma

**Comment by jeroenwittock** [comment]
This has been merged into develop branch through https://github.com/CiscoDevNet/terraform-provider-fmc/pull/114, we will push this into main shortly.

Thanks,
J
