### ISSUE TITLE
enhancement: resource security_zone - add type to read-only params in resource security_zone

### ISSUE THREAD

**Issue by mmaciejc** [CiscoDevNet/terraform-provider-fmc#131]
There is only id under [Read-Only]

    id (String) The ID of this resource.

We need type to be able to use it under accesspolicy

**Comment by snetlamu** [comment]
Thanks for bringing this to our notice! We are working to adding this.

**Comment by jeroenwittock** [comment]
This should be supported with version 1.4.6. This will become available later today.
