### ISSUE TITLE
tofu init: authentication signature from unknown issuer

### ISSUE THREAD

**Issue by tomvrugt** [CiscoDevNet/terraform-provider-fmc#162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
$ tofu -v
OpenTofu v1.6.2
on linux_amd64
```

### Affected Resource(s)

N/A

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    fmc = {
      source = "CiscoDevNet/fmc"
    }
  }
}
```

### Expected Behavior
FMC provider is installable from OpenTofu registry

### Actual Behavior

Installing the FMC provider from OpenTofu registry fails. Please submit GPG public key to https://github.com/opentofu/registry.

### Steps to Reproduce

```bash
$tofu init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of ciscodevnet/fmc...
- Installing ciscodevnet/fmc v1.4.8...
╷
│ Error: Failed to install provider
│
│ Error while installing ciscodevnet/fmc v1.4.8: authentication signature from unknown issuer
╵
```

### References

* #0000

**Comment by jeroenwittock** [comment]
We are working on make our provider available. Hopefully in the next few days everything falls into place.

**Comment by oborys** [comment]
@tomvrugt GPG public key was submitted https://github.com/opentofu/registry/issues/888. Please try to install the provider from the OpenTofu registry

**Comment by tomvrugt** [comment]
> @tomvrugt GPG public key was submitted [opentofu/registry#888](https://github.com/opentofu/registry/issues/888). Please try to install the provider from the OpenTofu registry

@oborys Install still fails. But PR https://github.com/opentofu/registry/pull/889 has not been merged into main yet. I'll await the merge and try again.

**Comment by oborys** [comment]
@tomvrugt I've updated the Key, and the PR has been merged. Please try again and let us know if we can close the issue.

**Comment by tomvrugt** [comment]
@oborys install now works! Thanks! Please go ahead and close the issue.
