### ISSUE TITLE
Please add the ability to import

### ISSUE THREAD

**Issue by txraider09** [CiscoDevNet/terraform-provider-fmc#2]
I have several existing NAT and ACP policies I would like to get imported into TF. When running a terraform import, I receive the following:

Error: resource fmc_ftd_nat_policies doesn't support import

**Comment by pedrojflores** [comment]
+1

**Comment by dalamanster** [comment]
terraform import of access and nat policies would help us a lot

This is the the tutorial how this should be made. Is there anybody willing to add this feature?  
[https://www.terraform.io/plugin/sdkv2/resources/import](https://www.terraform.io/plugin/sdkv2/resources/import)

**Comment by vladget** [comment]
+1

**Comment by jeroenwittock** [comment]
This has been created, it is now in develop (https://github.com/CiscoDevNet/terraform-provider-fmc/pull/103)
It will go to main in the next couple of days.
