### ISSUE TITLE
data source fmc_access_policy failing

### ISSUE THREAD

**Issue by HD-Sytner** [CiscoDevNet/terraform-provider-fmc#23]
Trying to use:

data "fmc_access_policies" "FTD" {
    name = "FTD"
}

Produces following error:
╷
│ Error: unable to get accessPolicy
│
│   with data.fmc_access_policies.access_policy,
│   on main.tf line 13, in data "fmc_access_policies" "access_policy":
│   13: data "fmc_access_policies" "access_policy" {
│
│ getting access policy by name/value: https://x.x.x.x/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies?expanded=false&filter=name:FTD - wrong status code: 400, error
│ category: FRAMEWORK, error severity: ERROR, error messages: [{filter query parameter 'name' is not supported.}]

Name is the only required argument.

**Comment by txraider09** [comment]
Please resolve this for FMC v7.3. I am running 7.3 and still seeing the issue.

**Comment by jeroenwittock** [comment]
We're investigating and will get back to you on this.

**Comment by kgreeshm** [comment]
Hi,
Could you please confirm me if you are still facing this issue , If yes please attach the screenshot of the error for better understanding.

Thanks 
Greeshma

**Comment by jeroenwittock** [comment]
With current version of terraform provider we are not seeing this issue. Hence we will close this one. However if you still see the problem, please let us know version of the provider you are using, as well as version of FMC. 

Thanks.
