### ISSUE TITLE
FMC NAT Device Assignment

### ISSUE THREAD

**Issue by jasonlmaynard** [CiscoDevNet/terraform-provider-fmc#3]
Perhaps missed it but looking to include both policy assignment for access control and NAT policies. Then deploy policies.

**Comment by adyanth** [comment]
Hey @jasonlmaynard 
The same resource `fmc_policy_devices_assignments` can assign both ACP and NAT Policy to the device. Please pass the NAT Policy ID and type to the resource and it should work. Reference: https://registry.terraform.io/providers/CiscoDevNet/fmc/latest/docs/resources/fmc_policy_devices_assignments#required

**Comment by adyanth** [comment]
As discussed, each policy is a separate resource.

**Comment by jasonlmaynard** [comment]
That worked!
