### ISSUE TITLE
unable to run terraform init for CiscoDevNet FMC on Apple Silicon Macbook pro

### ISSUE THREAD

**Issue by anilsonowal** [CiscoDevNet/terraform-provider-fmc#7]
When I run terraform init for my CiscoDevNet FMC project on my Apple Silicon macbook pro I get this error.

terraform init              
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding ciscodevnet/fmc versions matching "0.1.1"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/ciscodevnet/fmc v0.1.1 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵

**Comment by adyanth** [comment]
Need to add `darwin/arm64` for cross compiling.

**Comment by adyanth** [comment]
Please test now @anilsonowal I do not have an M1 Mac to test this right now.
